from playwright.sync_api import sync_playwright
import json, os
ROOT=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
URL="file://"+os.path.join(ROOT,"dist","preview.html").replace("\\","/")
os.makedirs(os.path.join(ROOT,"dist","dl"),exist_ok=True)
R=[]
def ok(n,c,x=""): R.append((("PASS" if c else "FAIL"),n,x))
with sync_playwright() as p:
    b=p.chromium.launch(); c=b.new_context(viewport={'width':1500,'height':1000},accept_downloads=True)
    pg=c.new_page(); errs=[]; pg.on("pageerror",lambda e:errs.append(str(e)))
    pg.goto(URL); pg.wait_for_timeout(800); pg.click('.tile[data-k="extension"]'); pg.wait_for_timeout(500)
    # floor
    pg.locator('button.step:has-text("Ground Floors")').click(); pg.wait_for_timeout(300)
    ok("F1 floor configurator present", pg.locator("#addFloor").count()==1)
    ok("F1 wall configurator absent here", pg.locator("#addWall").count()==0)
    u=pg.inner_text(".uval b").strip(); ok("F2 default 100 TF70 P/A 0.5 clay = 0.16", u=="0.16", u)
    pg.select_option('select[data-cf="pa"]',"1"); pg.wait_for_timeout(250)
    u2=pg.inner_text(".uval b").strip(); ok("F3 P/A 1.0 raises U", float(u2)>float(u), f"{u}->{u2}")
    pg.select_option('select[data-cf="kind"]',"timber"); pg.wait_for_timeout(300)
    ok("F4 timber shows joist controls", pg.locator('select[data-cf="joistDepth"]').count()==1 and pg.locator('select[data-cf="edge"]').count()==0)
    u3=pg.inner_text(".uval b").strip(); ok("F4 suspended timber 100 TF70 fails 0.18", pg.locator(".uval.bad").count()==1, u3)
    pg.select_option('select[data-cf="kind"]',"solid"); pg.select_option('select[data-cf="pa"]',"0.5"); pg.wait_for_timeout(250)
    pg.click("#addFloor"); pg.wait_for_timeout(400)
    ok("F5 floor added and numbered GF", any(t.strip().startswith("GF") for t in pg.locator('#stage .card.on .tag').all_inner_texts()))
    ok("F5 ISO 13370 steps in preview", "Characteristic dimension" in pg.inner_text("#paper"))
    # roof
    pg.locator('button.step:has-text("Roofs")').click(); pg.wait_for_timeout(300)
    ok("R1 roof configurator present", pg.locator("#addRoof").count()==1)
    u=pg.inner_text(".uval b").strip(); ok("R2 default warm deck 150 TR27 = 0.15", u=="0.15", u)
    pg.select_option('select[data-cf="kind"]',"rafter"); pg.wait_for_timeout(300)
    u=pg.inner_text(".uval b").strip(); ok("R3 default rafter 150 K107 + 62.5 K118 = 0.14 (lambda 0.019 verified)", u=="0.14", u)
    pg.select_option('select[data-cf="rThick"]',"100"); pg.select_option('select[data-cf="under"]',"k118_375"); pg.wait_for_timeout(300)
    u=pg.inner_text(".uval b").strip(); ok("R4 old loft spec 100 + 37.5 = 0.21 and FAILS", u=="0.21" and pg.locator(".uval.bad").count()==1, u)
    warn=pg.locator(".cfgwarn").count()
    pg.select_option('select[data-cf="rThick"]',"200"); pg.wait_for_timeout(250)
    ok("R5 over-depth warning shown", pg.locator(".cfgwarn").count()==1 and "exceeds rafter depth" in pg.inner_text(".cfgwarn"))
    pg.select_option('select[data-cf="kind"]',"ceiling"); pg.wait_for_timeout(300)
    u=pg.inner_text(".uval b").strip(); ok("R6 cold roof 100+300 = 0.11", u=="0.11", u)
    pg.click("#addRoof"); pg.wait_for_timeout(400)
    ok("R7 roof added and numbered RF", any(t.strip().startswith("RF") for t in pg.locator('#stage .card.on .tag').all_inner_texts()))
    # both customs coexist, refs distinct
    paper=pg.inner_text("#paper")
    ok("X1 both customs in schedule", "Solid Ground Floor" in paper and "Ceiling Level" in paper)
    ok("X1 working section lists both", paper.upper().count("COMBINED METHOD")>=1 and "Characteristic dimension" in paper)
    with pg.expect_download(timeout=40000) as d: pg.click("#btnPdf")
    dd=d.value; path="dl/fr.pdf"; dd.save_as(path)
    ok("X2 PDF with floor+roof working", os.path.getsize(path)>40000, f"{os.path.getsize(path)} bytes")
    # wall configurator still works alongside
    pg.locator('button.step:has-text("External Walls")').click(); pg.wait_for_timeout(300)
    pg.select_option('select[data-cf="gapLevel"]',"0"); pg.wait_for_timeout(250)
    ok("X3 wall configurator unaffected", pg.inner_text(".uval b").strip()=="0.17")
    print(json.dumps([{"r":a,"t":b,"x":c} for a,b,c in R])); print("PAGE ERRORS:",errs[:4]); b.close()
