<?php
/* The specification tool's store.
 *
 * Speaks the small interface the app already used inside the Claude artifact — get, set and
 * delete a document, and list a collection — so the app's own save and load logic is unchanged.
 * src/serverstore.js is the client half.
 *
 * THE ONE RULE HERE. Every row is reached by the practice on the session and never by an
 * identifier the client sends. A job id arrives from the browser, but it is only ever used
 * inside a WHERE that also pins practice_id, so naming another practice's job returns nothing
 * and writing to one is impossible. That is the per-practice separation the artifact could
 * never have, because the artifact had no idea who was looking at it.
 */

declare(strict_types=1);
require __DIR__ . '/app/bootstrap.php';

header('Content-Type: application/json; charset=utf-8');
header('Cache-Control: no-store');

const MAX_JOB_BYTES     = 3000000;   // a job carries its own build-up text and working
const MAX_PROFILE_BYTES = 2000000;   // a practice logo is a data URI and can be large

function out(int $code, array $body): never {
    http_response_code($code);
    echo json_encode($body, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    exit;
}
function fail(int $code, string $msg): never { out($code, ['ok' => false, 'error' => $msg]); }

if (($_SERVER['REQUEST_METHOD'] ?? '') !== 'POST') fail(405, 'Send this by POST.');

$u = current_user();
if (!$u)                fail(401, 'Not signed in.');
if (!app_access($u))    fail(403, 'This account cannot open the specification tool yet.');
/* Same gate as app.php, or the store would stay open to a practice the tool is shut to. */
$r = open_refusal($u);
if ($r !== '')          fail(402, $r);

/* CSRF: the token is put into the page by app.php and echoed back as a header. Same-origin
   fetch only, so a cross-site page cannot read it to send one. */
$sent = (string)($_SERVER['HTTP_X_CSRF'] ?? '');
if ($sent === '' || !hash_equals(csrf_token(), $sent)) fail(400, 'The session token did not match. Reload the tool.');

$raw = file_get_contents('php://input');
if ($raw === false || strlen($raw) > MAX_JOB_BYTES + 100000) fail(413, 'That is larger than the store accepts.');
$in = json_decode((string)$raw, true);
if (!is_array($in)) fail(400, 'Malformed request.');

$op  = (string)($in['op'] ?? '');
$pid = (int)$u['practice_id'];

/* Only two document paths exist. Anything else is refused rather than interpreted, so a path
   can never be used to reach a row this endpoint was not written to serve. */
function parse_path(string $path): array {
    if ($path === 'practice/profile') return ['profile', ''];
    if (preg_match('#^jobs/([A-Za-z0-9_-]{1,48})$#', $path, $m)) return ['job', $m[1]];
    return ['', ''];
}

switch ($op) {

case 'doc.get': {
    [$kind, $id] = parse_path((string)($in['path'] ?? ''));
    if ($kind === 'job') {
        $r = row('SELECT payload FROM jobs WHERE id = ? AND practice_id = ?', [$id, $pid]);
        out(200, ['ok' => true, 'data' => $r ? json_decode($r['payload'], true) : null]);
    }
    if ($kind === 'profile') {
        $r = row('SELECT payload FROM practice_profile WHERE practice_id = ?', [$pid]);
        out(200, ['ok' => true, 'data' => $r ? json_decode($r['payload'], true) : null]);
    }
    fail(400, 'Unknown path.');
}

case 'doc.set': {
    [$kind, $id] = parse_path((string)($in['path'] ?? ''));
    $data = $in['data'] ?? null;
    if (!is_array($data)) fail(400, 'Nothing to store.');
    if (!throttle('api-write:' . $u['id'], 600, 3600)) fail(429, 'Too many saves in the last hour. The job is safe in this browser.');

    if ($kind === 'job') {
        $payload = json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        if ($payload === false || strlen($payload) > MAX_JOB_BYTES) fail(413, 'That job is larger than the store accepts.');
        $d    = is_array($data['data'] ?? null) ? $data['data'] : [];
        $type = mb_substr((string)($data['type'] ?? ''), 0, 24);
        $jobNo= mb_substr((string)($d['job'] ?? ''), 0, 80);
        $title= mb_substr(trim((string)($d['project'] ?? $d['address'] ?? '')), 0, 240);
        $rev  = mb_substr((string)($d['rev'] ?? ''), 0, 12);
        $exists = row('SELECT id FROM jobs WHERE id = ? AND practice_id = ?', [$id, $pid]);
        if ($exists) {
            q('UPDATE jobs SET type = ?, job_no = ?, title = ?, rev = ?, payload = ?, updated_at = ?, user_id = ? WHERE id = ? AND practice_id = ?',
              [$type, $jobNo, $title, $rev, $payload, now(), (int)$u['id'], $id, $pid]);
        } else {
            /* Someone else's job with this id must not be adopted, and an id is only ever
               generated by the client for its own new job, so a collision is a refusal. */
            if (row('SELECT id FROM jobs WHERE id = ?', [$id])) fail(409, 'That job belongs to another practice.');
            q('INSERT INTO jobs (id, practice_id, user_id, type, job_no, title, rev, payload, created_at, updated_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
              [$id, $pid, (int)$u['id'], $type, $jobNo, $title, $rev, $payload, now(), now()]);
        }
        out(200, ['ok' => true]);
    }
    if ($kind === 'profile') {
        $payload = json_encode($data, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
        if ($payload === false || strlen($payload) > MAX_PROFILE_BYTES) fail(413, 'That practice profile is larger than the store accepts. A smaller logo will fix it.');
        if (row('SELECT practice_id FROM practice_profile WHERE practice_id = ?', [$pid]))
            q('UPDATE practice_profile SET payload = ?, updated_at = ? WHERE practice_id = ?', [$payload, now(), $pid]);
        else
            q('INSERT INTO practice_profile (practice_id, payload, updated_at) VALUES (?, ?, ?)', [$pid, $payload, now()]);
        /* Keep the account page and the specification cover telling the same story. */
        $name = mb_substr(trim((string)($data['name'] ?? '')), 0, 150);
        $contact = mb_strtolower(trim((string)($data['email'] ?? '')));
        if (!valid_email($contact)) $contact = '';
        if ($name !== '') q('UPDATE practices SET name = ?, designer = ?, address = ?, phone = ?, contact_email = ? WHERE id = ?',
            [$name, mb_substr((string)($data['designer'] ?? ''), 0, 120), mb_substr((string)($data['addr'] ?? ''), 0, 400),
             mb_substr((string)($data['phone'] ?? ''), 0, 40), $contact, $pid]);
        out(200, ['ok' => true]);
    }
    fail(400, 'Unknown path.');
}

case 'doc.del': {
    [$kind, $id] = parse_path((string)($in['path'] ?? ''));
    if ($kind !== 'job') fail(400, 'Only a job can be deleted here.');
    q('DELETE FROM jobs WHERE id = ? AND practice_id = ?', [$id, $pid]);
    out(200, ['ok' => true]);
}

/* Issuing a specification. A subscription simply says yes; per-spec spends one credit, here,
   at the moment of issue — the app records the revision in its own history either way. The
   client is told plainly when there is nothing to spend, so it can stop before writing an
   issue into a job's history that was never paid for. */
case 'spec.issue': {
    $jobId = (string)($in['job'] ?? '');
    if (!preg_match('#^[A-Za-z0-9_-]{1,48}$#', $jobId)) fail(400, 'Which job?');
    /* The revision being issued. It makes the charge idempotent, so the app can ask before it
       builds the document and a failed build does not cost a credit. */
    $rev = strtoupper(trim((string)($in['rev'] ?? '')));
    if ($rev !== '' && !preg_match('#^[A-Z]{0,4}[0-9]{1,4}$#', $rev)) $rev = '';
    /* The decision itself is in billing.php, where it can be tested without a web server. */
    $r = issue_charge($pid, $u, $jobId, $rev);
    if (!$r['ok']) fail(402, (string)$r['error']);
    out(200, ['ok' => true, 'charged' => $r['charged'], 'already' => $r['already'],
              'credits' => $r['credits'], 'why' => $r['why']]);
}

case 'coll.get': {
    if ((string)($in['name'] ?? '') !== 'jobs') fail(400, 'Unknown collection.');
    $limit = max(1, min(200, (int)($in['limit'] ?? 100)));
    $docs = [];
    foreach (rows('SELECT id, payload FROM jobs WHERE practice_id = ? ORDER BY updated_at DESC LIMIT ' . $limit, [$pid]) as $r) {
        $d = json_decode($r['payload'], true);
        if (is_array($d)) $docs[] = ['id' => $r['id'], 'data' => $d];
    }
    out(200, ['ok' => true, 'docs' => $docs]);
}

}
fail(400, 'Unknown operation.');
