# -*- coding: utf-8 -*-
"""Build the font the PDF export embeds — src/fonts.js.

The PDF referenced Helvetica rather than carrying a font, which is fine until it is not: the
standard fourteen are *referenced*, not embedded, so a viewer substitutes whatever it has, and a
viewer whose substitute lacks a glyph drops it. The characters at risk are the ones this library
uses most — the superscript two in every U-value, the em dash in every heading, the degree sign in
every hot water clause. A specification that reaches building control reading "W/mK" where it
should read "W/m²K" has said something different.

So the font is embedded. DejaVu Sans, whose licence explicitly permits embedding, subset to the
characters the library actually uses: printable ASCII plus the twelve non-ASCII characters that
appear anywhere in data/, plus a handful of typographic ones the app itself writes. That is a few
kilobytes rather than the three hundred a whole font would cost.

Run it when the character set changes. It writes src/fonts.js, which build.py assembles into the
app like any other source file.
"""
import base64, io, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# printable ASCII, then everything the library and the app can put on a page
EXTRA = (
    "£"      # £
    "°"      # degree
    "²³"  # superscript two and three
    "·"      # middle dot
    "½¼¾"  # halves and quarters
    "×"      # multiplication sign
    "éèàçöüä"  # the accents a practice name can carry
    "λΨψΔπ"              # lambda, psi, delta, pi
    "–—"          # en and em dash
    "‘’“”"  # curly quotes
    "…"      # ellipsis
    "•"      # bullet
    "≤≥±−≈≠"  # <= >= +/- minus approx not-equal
    "øØ⌀"    # diameter
    "€"      # euro
)
CHARS = "".join(chr(c) for c in range(0x20, 0x7F)) + EXTRA

FACES = [("DejaVuSans.ttf", "normal"), ("DejaVuSans-Bold.ttf", "bold")]


def source_ttf(name):
    """DejaVu ships with matplotlib, which this repository already depends on for nothing else —
    so if it is not there, say what to do rather than failing obscurely."""
    try:
        import matplotlib
    except ImportError:
        sys.exit("matplotlib is needed for the DejaVu font files:  python -m pip install matplotlib")
    p = os.path.join(os.path.dirname(matplotlib.__file__), "mpl-data", "fonts", "ttf", name)
    if not os.path.exists(p):
        sys.exit("cannot find %s next to matplotlib" % name)
    return p


def subset(path, chars):
    from fontTools import subset as fts
    from fontTools.ttLib import TTFont
    font = TTFont(path)
    opts = fts.Options()
    opts.layout_features = ["*"]
    opts.notdef_outline = True
    opts.recalc_bounds = True
    opts.drop_tables += ["FFTM"]
    s = fts.Subsetter(options=opts)
    s.populate(text=chars)
    s.subset(font)
    buf = io.BytesIO()
    font.save(buf)
    return buf.getvalue()


def main():
    out = ["""/* ================= The font the PDF carries =================
   GENERATED by docgen/make_pdf_font.py — do not edit by hand.

   jsPDF's standard fourteen fonts are REFERENCED, not embedded, so the viewer substitutes
   whatever it has. A substitute that lacks a glyph drops it, and the glyphs this library leans on
   are the superscript two in every U-value and the em dash in every heading. A specification that
   reaches building control reading W/mK where it should read W/m²K has said something different.

   DejaVu Sans, whose licence permits embedding, subset to the characters this library uses.
   %d characters, regular and bold.
*/""" % len(CHARS)]
    total = 0
    for name, style in FACES:
        data = subset(source_ttf(name), CHARS)
        total += len(data)
        b64 = base64.b64encode(data).decode("ascii")
        out.append("const SPECLINE_FONT_%s = \"%s\";" % (style.upper(), b64))
    out.append("""
/* The characters the subset actually contains. safe() keeps exactly these and maps or drops the
   rest: a character the font does not carry renders as an empty box, which is worse than a
   substitution that reads correctly. */
const SPECLINE_FONT_CHARS = %s;

/* Registers the font on a jsPDF document and returns its name, or null if anything goes wrong —
   in which case the caller stays on Helvetica and the export still works. */
function splineFont(doc){
  try{
    doc.addFileToVFS("Specline-normal.ttf", SPECLINE_FONT_NORMAL);
    doc.addFont("Specline-normal.ttf", "Specline", "normal");
    doc.addFileToVFS("Specline-bold.ttf", SPECLINE_FONT_BOLD);
    doc.addFont("Specline-bold.ttf", "Specline", "bold");
    return "Specline";
  }catch(e){ console.error("font embedding failed; falling back to Helvetica", e); return null; }
}""" % ("\"" + CHARS.replace("\\", "\\\\").replace('"', '\\"') + "\""))
    path = os.path.join(ROOT, "src", "fonts.js")
    io.open(path, "w", encoding="utf-8").write("\n".join(out) + "\n")
    print("wrote src/fonts.js — %d characters, %d bytes of font, %d bytes of source"
          % (len(CHARS), total, os.path.getsize(path)))


if __name__ == "__main__":
    main()
