import sys, subprocess
import os
sys.path.insert(0,os.path.dirname(os.path.abspath(__file__)))
HERE=os.path.dirname(os.path.abspath(__file__))
OUT=os.path.join(os.path.dirname(HERE),'output'); os.makedirs(OUT,exist_ok=True)
# SY Design Studio's own QA report on the library, so it pins the in-house profile
# rather than reading whichever practice is installed. See dedupe_report.py.
os.environ.setdefault('SPECLINE_PRACTICE_SOURCE','brand')
from build_spec import *
from brand import _rule, _shade
def sp(d,t,size=9.5,color=None,bold=False):
    p=d.add_paragraph(); p.paragraph_format.space_after=Pt(4); r=p.add_run(t); r.font.size=Pt(size); r.font.bold=bold
    if color: r.font.color.rgb=color
    return p
def bullet(d,t):
    p=d.add_paragraph(); p.paragraph_format.left_indent=Mm(6); p.paragraph_format.first_line_indent=Mm(-4); p.paragraph_format.space_after=Pt(2)
    r=p.add_run("•  "); r.font.color.rgb=ACCENT; r.font.bold=True; r.font.size=Pt(9.5)
    r=p.add_run(t); r.font.size=Pt(9.5)
def verdict(d,v,why):
    p=d.add_paragraph(); p.paragraph_format.space_after=Pt(4)
    r=p.add_run("VERDICT  "); r.font.bold=True; r.font.size=Pt(9); r.font.color.rgb=ACCENT
    r=p.add_run(v); r.font.bold=True; r.font.size=Pt(10); r.font.color.rgb=DARK
    sp(d,why)
meta=dict(type="Plan-Check Stress Test of the Specification Library", project="All eight project types",
  address="Simulated Full Plans review — test projects in Hounslow, Feltham, Hillingdon, Richmond and Kingston", client="SY Design Studio Ltd (internal)", job="LIBRARY", la="Simulated LA building control",
  application="Internal QA review", author="Prepared with Claude for Salman Yousaf", date="5 September 2026", rev="R01")
d=new_doc(); headers(d,meta); cover(d,meta)          # the logo comes from the practice profile
h1(d,"Purpose and Method","1.0")
sp(d,"Each of the eight specifications in the library was reviewed as an experienced local-authority plan checker would review a Full Plans submission, against a realistic test project for that type, using the current English Approved Documents (2024–2026 editions) and the Building Regulations 2010 as amended. The review was carried out after the BuildingRegs4Plans coverage check and the material verification, so it tests the library as it now stands. Verdicts follow plan-check practice: almost every real submission is approved with conditions or a request for further information, because the specification is a library and the drawings, the engineer's design and the energy assessment supply the project-specific facts. The value of this report is in the 'further information' lists — they show where a plan checker would still write to us — and the corrections made in response are recorded at the end.")
sp(d,"Scores are out of 10 for submission-readiness of the specification alone. Items marked (c) are inherently project-specific and are not defects in the library.")
R=[
("House Extension","5m deep single-storey rear extension to a 1930s semi in Hounslow; cavity walls, warm deck roof with rooflights, existing suspended floor, extension covers existing air bricks, boiler relocated.","APPROVE WITH CONDITIONS / FURTHER INFORMATION","Build-ups are sound and self-calculating; the pack carried duplicated notes and left the relocated boiler and the enclosed rear-wall services unresolved.",
 ["Existing sub-floor ventilation ducted beneath the new slab (AD C)","Full-fill cavity wall 0.17 with block conductivity and fallback (AD L Table 4.2)","Warm deck 0.15 with fastener correction, 1:80 design fall, 150mm upstands","25% opening-area rule including closed-off openings","Unprotected-area figures and BROOF(t4) (AD B Section 11/12)","Extract 30/60 l/s, 8000mm² background, purge 1/20 (AD F)","Temperature factor 0.75 and vapour control continuity (C2)","Build-over / 3m sewer agreement"],
 ["Regulation 46A commencement definition for a horizontal extension (sub-structure and ground floor, not 15%) — CORRECTED","Duplicate Regulation 16 and HMO notes — CORRECTED (duplicates removed)","Roof-only steel in a single-storey extension needs no fire protection; floor-carrying steel does — CORRECTED (clarified)","Solid floor GF1 gave '80mm Kingspan' with no product or calculation — CORRECTED (K103, 0.17 at P/A 0.5, 0.18 at 0.7, 100mm option)","Relocated boiler: flue terminal to AD J Diagram 3.4 clearances from new rooflights/boundary — project item, add to drawings","Existing SVP, gullies and downpipes enclosed by the extension: stack to terminate 900mm above rooflights — add to drawings","Inner-room consequences of an open-plan kitchen/dining — resolve on plan","(c) Beams, padstones, foundation depth versus trees, boundary distance, rooflight positions, level junction with existing floor"],
 ["Air-brick ducts omitted or crushed before the slab is poured","Full-fill boards cut short with mortar snots; no cavity tray at the abutment","Relocated flue too close to a rooflight or boundary"],"6 → 7"),
("Loft Conversion","Rear dormer with hip to gable to a two-storey 1930s semi in Feltham; bedroom and en-suite, new stair over existing, party wall to neighbour's unconverted loft.","APPROVE WITH CONDITIONS / FURTHER INFORMATION","Fire strategy and stair are correctly framed; the new floor's fire resistance with a retained ceiling and one build-up header needed correction.",
 ["Three escape options with E20 doors to all habitable rooms including existing (AD B 2.5–2.21)","Escape windows correctly rejected above 4.5m","30 minutes for a three-storey house, 60 for the separating wall","Room-in-roof 0.15 with rafter bridging quantified; downlighter hoods","Party wall carried to the roof covering and fire stopped; cavity bypass sealed","Stair to AD K including the 1.9/1.8m loft headroom relaxation","E2 40 dB floor and partitions; en-suite 15 l/s"],
 ["'Existing Gable or Flank Wall' header claimed 0.18 with 62.5mm board, which calculates at 0.30 — CORRECTED (72.5mm, 0.26, retained-element target 0.30)","New loft floor REI 30 where the existing ceiling is retained below the new joists — CORRECTED (as-built options stated)","Alarm grade D2 LD3 in one note and D1 LD2 in another — CORRECTED (D1 LD2 adopted, AD B minimum stated)","Party wall to the neighbour's loft described as a thermal element — it is another building; presented as recommended practice","Dormer cheek within 1m of the boundary: 30 minutes from both sides — covered in the render/timber cheek build-ups; check on plan","Masonry hip-to-gable base detail on a solid flank wall — add to drawings","(c) Beams, padstones, flank wall and foundation adequacy, rafter deepening, dormer framing"],
 ["Existing hollow-core doors left in place; kitchen door omitted","Party wall not carried to the roof covering behind the new gable","Between-rafter board thinned or the 50mm ventilation gap lost"],"7 → 8"),
("Flat Conversion","Three-storey Victorian terrace in Hounslow into a ground-floor flat and upper maisonette; timber separating floor, common entrance hall, gas combis, two rear parking spaces.","APPROVE WITH CONDITIONS / FURTHER INFORMATION","Regulation 6 framing, the Part E regime and the common-stair strategy are right; the separating floor was specified to two standards and one Part L threshold was misstated.",
 ["Regulation 6 list including Q1, S2, H6 and C1(2); A and M correctly excluded","43/64 dB with mandatory pre-completion testing and no Robust Details route","60-minute compartmentation above 5m, FD30S and FD20 doors, 9m travel","Small single-stair building with 1m² vent and emergency lighting","Fire authority consultation and Regulation 38 handover","Renovated floor 0.25 and roof 0.16 with worked figures","PAS 24 doorsets certified for fire and security; 7kW charge points","10,000mm² background ventilation for single-storey flats; System 3/4 triggers"],
 ["Separating floor ceiling 2 x 12.5mm for Part E versus 2 x 15mm tested system for 60 minutes — CORRECTED (one build-up now satisfies both)","Internal wall insulation note called 0.30 'the threshold' (0.70 is the threshold, 0.30 the improved value) — CORRECTED","Retained stud or lath partitions becoming separating walls to the common hall — CORRECTED (upgrade specified)","Combi flue routes through the compartment floor and terminal near the communal entrance — add to drawings","S2 wording versus two rear parking spaces — state the charge-point provision on the site plan","(c) Floor loading with platform floor, top-storey height, boundary distances, bin store, meter positions, G2 calculation per flat"],
 ["Floating floor bridged at skirtings and thresholds — impact test failure","Ceiling built to the Part E version only; downlighters cut in","Entrance doorsets not certificated for both FD30S and PAS 24"],"7 → 8"),
("Garage Conversion","Integral single garage under a bedroom in a 1980s detached house in Hillingdon to a bedroom with en-suite; door infilled, part retained for storage.","APPROVE WITH CONDITIONS / FURTHER INFORMATION","The most project-adapted of the eight; conditions concern what 'retained for storage' means and the separation as built.",
 ["Table 4.3 retained values (0.30/0.55/0.25/0.16) and Table 4.2 new values with every build-up calculated","Threshold foundation exposed and remade to 1000mm in clay","Infill cavity wall 0.17 with starter ties, tray, DPC at 150mm and drive levels","Separation to a retained garage REI 30, FD30S self-closing, 100mm step, wall to roof covering, also a 0.18 thermal element","Egress window, inner-room rule and alarm grade","Cavity barriers at the first-floor line","AD F figures and 10mm undercuts","Part Q correctly stated as not applicable, PAS 24 as good practice"],
 ["Applicability wording: Regulations 22 and 23 (change to energy status / renovation) rather than 'material alteration' — CORRECTED in wording","Retained 'store' versus retained 'garage' — state on the drawings which regime applies","En-suite WC branch invert with a raised floor; gravity WC exists upstairs so a macerator is permissible","Bedroom under bedroom: E2 ceiling lining 10 kg/m² — covered by the ceiling upgrade note","1980s cavity walls may already be partial-filled — borescope survey is specified","(c) Door lintel and pier, threshold foundation, store wall position, levels, flue"],
 ["Threshold footing not exposed before the infill is built","DPM not lapped to the DPC; lining fixed to a damp single-leaf plinth","Head of the store wall left open above the ceiling; FD30S without a closer"],"8"),
("New Build","Detached four-bed two-storey house in Hillingdon; cavity masonry, beam and block floor, trussed roof with room-in-roof over the garage wing, ASHP and PV, M4(2) by condition, private drive, public sewer in the road.","APPROVE WITH CONDITIONS / FURTHER INFORMATION","Technically strong and largely accurate; the gap was fire-service access on a private drive.",
 ["Regulation 16/46A notice regime and Part 2A completion statements","Part L 2021 notional and limiting values, SAP/BREL evidence, Regulation 25A, every-dwelling pressure test","Part F Tables 1.1/1.3, System 1 prohibition below 5 m³/(h·m²), commissioning sheet","Grade D1 LD2 alarms, egress windows, integral garage separation, unprotected-area table and BROOF(t4)","Beam and block void 150mm and ventilation, DPC 150mm, tie and movement-joint spacings to PD 6697, AD A opening rules","Parts K, M4(2), Q, S, R and G handled with the right figures"],
 ["B5 access: pump appliance within 45m of every point in the dwelling from a 3.7m drive with turning where over 20m; hydrant within 90m — CORRECTED (note added)","Room-in-roof over attic trusses: state the fallback where the truss designer sets shallower rafters — add to drawings","AD K minor points on doors swinging over landings and window restrictors — reviewed","ASHP: Domestic Building Services Compliance Guide efficiencies and Regulation 40 information — covered generically; add the MCS design to the pack","(c) Engineer's foundations and truss layout, SAP 10.2, Part O assessment, drainage layout and Section 106 consent, site investigation, M4(2) room check"],
 ["Full-fill phenolic boards with mortar snots and no cavity board — BREL photo failure","Vapour control and insulation continuity at the attic-truss eaves and the garage-wing separation","Telescopic vents obstructed; air-barrier penetrations unsealed"],"8"),
("New Build Flats","Four-storey block of nine flats in Hounslow (top floor 10.4m), concrete frame with masonry infill, single stair, communal ASHP heat network, undercroft parking, one M4(3) flat.","APPROVE WITH CONDITIONS / FURTHER INFORMATION","Good fire and acoustic framework for a sub-11m single-stair block; the undercroft car park was barely addressed and one Part L clause was outdated.",
 ["Height thresholds 4.5/5/11/18m and the measurement rule","60-minute compartmentation, sprinklers only above 11m, Regulation 38 handover","Common escape: 7.5m/30m travel, 1.5m² and 1m² vents, dual-certificated FD30S doorsets, 9m within flats","Part E 45/62 dB, Robust Details or one-in-ten testing, E3 absorption","AD A Consequence Class 2A for four storeys","Part F for single-aspect flats, Part O with TM59, M4(2)/(3) widths and lift dimensions, Part S load management, H6 refuse","B5 route 3.7m and 12.5 tonnes, hydrants within 90m"],
 ["Airtightness sample testing with 'tested value + 2' — withdrawn in AD L 2021 — CORRECTED (every flat tested)","Separating wall build-up omitted the full cavity fill needed for a zero party-wall U-value — CORRECTED","Undercroft car park: ventilation, protected lobby to the single stair, escape, linings, EV siting — CORRECTED (note added)","M4(3) flat above entrance level makes the lift mandatory — CORRECTED","Frame fire protection and slab-edge details for the infill wall — covered in the structure and walls notes; check on drawings","Heat network plant room separation and risers as protected shafts — add to fire strategy","(c) Fire strategy, structural design, per-flat SAPs, TM59, Robust Details registration, LLFA drainage strategy"],
 ["Unrecorded or failed fire stopping at risers and slab penetrations","Resilient layer bridged at skirtings and thresholds","Flat entrance doorsets installed contrary to their certification; vent commissioning"],"7 → 8"),
("Basement Conversion","New basement under a Victorian terrace in Richmond: family room, bedroom and shower room, 2.7m deep, front lightwell, party walls both sides, clay with a perched water table, existing drains under the house.","APPROVE WITH CONDITIONS / FURTHER INFORMATION","BS 8102:2022 Grade 3 combined protection, underpinning and escape are handled properly; the drainage clauses needed reconciling.",
 ["BS 8102:2022 Grade 3 with two types of protection, CSSW specialist, design statement, duplicate pumps with battery back-up and alarm","Hit-and-miss underpinning in bays of not more than 1m with dry-pack, inspection and monitoring","Basement escape by egress window or door to a lightwell or a protected stair; REI 30 floor over; alarms extended","AD L Tables 4.2/4.3 with ISO 13370 below-ground values","AD K stair with the loft headroom relaxation correctly rejected; 1100mm lightwell guarding","Heave, uplift, dewatering and the Flood Zone 3 sleeping restriction"],
 ["Sump discharge 'to surface water or foul' contradicted the pumps note — CORRECTED (surface water or combined sewer with consent; never a separate foul drain)","Egress window sill given only as 'not more than 1100mm' — CORRECTED (800–1100mm)","Shared drains in a terrace are public sewers since 2011: build-over or diversion agreement — CORRECTED","Type A on inaccessible party walls with a perched water table — the design statement is to confirm a negative-side Type A or Type B plus C","Timber battens in the drained zone — metal studs preferred and stated","(c) Ground investigation with standpipes, underpinning method statement, waterproofing design statement, party wall awards, CCTV survey"],
 ["Membrane penetrated by non-proprietary fixings; perimeter channel buried","Adjacent underpinning bays open together or left overnight","Vapour control layer discontinuous behind the lining; sump not commissioned by filling"],"8"),
("Garage Build","Detached double garage (39m²) with a home office over, 1m from the rear boundary, pitched roof, on the house electrics, in Kingston.","APPROVE WITH CONDITIONS / FURTHER INFORMATION","Correctly identifies the building as not exempt, but was written for an unheated single-storey garage; the heated office over was left to cross-references.",
 ["Schedule 2 Class 6/7 exemption analysis and Part P notification regardless of exemption","AD A Section 2C single-leaf limits with an engineer required for a room over","Foundations 750/1000mm, NHBC 4.2 trees, AD A fallback; lintel bearing and fire protection","Boundary fire spread: 30 minutes both sides within 1m, BROOF(t4) within 6m, eaves not fence","Garage-to-dwelling separation REI 30, FD30S and step; fuel and interceptor drainage; soakaway 5m","Ties, movement, DPC and cavity tray notes complete"],
 ["Heated room over: Part L Volume 2 route, floor over the garage REI 30 and 0.18, stair, escape window or protected stair, alarms, Part F Volume 2 ventilation, sub-main — CORRECTED (new note)","Two-day notice wrongly called a commencement notice — CORRECTED","Duplicate leadwork note — CORRECTED","Boundary wording '1m² in total' versus '1m² each 4m apart' — the shared external fire spread note governs","(c) Engineer's design for the two-storey structure, boundary survey, U-value or BRUKL calculations"],
 ["Fire-resisting ceiling and beam protection between garage and office omitted","Eaves or gutter bringing the rear wall within 1m of the boundary","Office roof vapour control continuity; Part P notification of the sub-main"],"5 → 7"),
]
n=1
for name,proj,v,why,passes,fi,risks,score in R:
    n+=1; h1(d,name+" — plan-check",f"{n}.0")
    sp(d,"Test project: "+proj,9,MID)
    verdict(d,v,why)
    h2(d,"Would pass on")
    for x in passes: bullet(d,x)
    h2(d,"Further information a plan checker would request (and what was done)")
    for x in fi: bullet(d,x)
    h2(d,"Site inspection risk")
    for x in risks: bullet(d,x)
    p=sp(d,"Submission-readiness score: "+score+" / 10",10,ACCENT,True)
h1(d,"Corrections Made in Response","10.0")
for x in ["Regulation 46A commencement definition extended to horizontal extensions in every type; duplicated notice and HMO notes removed from the House Extension.",
 "House Extension solid floor GF1 now names Kingspan K103 with calculated U-values at two perimeter/area ratios; roof-only steelwork clarified.",
 "Loft: existing gable wall build-up corrected to 72.5mm insulated plasterboard at 0.26 W/m²K against the retained-element value of 0.30; alarm grade fixed at D1 LD2; new floor REI 30 with a retained ceiling given as-built options.",
 "Flat Conversion: separating floor ceiling now a tested 60-minute system where the compartment period requires it; threshold/improved wording corrected; retained stud partitions becoming separating walls specified.",
 "Basement: sump discharge, egress window sill (800–1100mm) and the public-sewer status of shared drains corrected.",
 "New Build: B5 fire-service access note added. New Build Flats: sample pressure testing removed, party wall full fill added, undercroft car park note added, lift made mandatory for M4(3) above entrance level.",
 "Garage Build: 'Home Office or Room Over the Garage' note added covering Part L Volume 2, the REI 30 floor, stair, escape, ventilation and electrics; duplicate leadwork note removed; notice wording corrected.",
 "Across all types after the BuildingRegs4Plans specification-text review: Regulation 16 notices, heating systems (92% ErP, 55°C, underfloor heating to BS EN 1264, unvented G3, TMV 48°C), chimneys and stoves (Part J), external fire spread with the unprotected-area table, off-mains drainage, drainage depths and branch limits, AD F figures and commissioning, stair detail, radon detail, foundation fallback dimensions, lintels and fire protection, movement joints and ties to PD 6697, leadwork, permitted development limits, HMO, sub-floor ventilation under extensions, rooflights, Part E testing and Robust Details evidence, Part O openings and entrapment, flat entrance door hardware, existing timber-frame wall upgrade.",
 "Verified corrections: renovated roofs of every type improved to 0.16 W/m²K (AD L 2021 Table 4.3 has one roof row); cavity concrete fill 225mm below DPC (AD C); oversite 100mm concrete or 50mm on a DPM (AD C); 50mm ventilated void above rafter-level insulation under a non-breathable underlay (BS 5250); all fixed lighting 75 lm/W (AD L 2021, no 75% rule); safety glazing zones 800/1500/300mm (AD K); AD M Table 1.1 corridor widths and M4(3) storage by bedroom count; drain cover 600/900mm and drainage field 15m from buildings (AD H); PD 6697 tie rule at jambs (one tie per 300mm within 225mm)."]:
    bullet(d,x)
h1(d,"What Remains Open","11.0")
for x in ["Every U-value in the library is calculated to BS EN ISO 6946 / 13370 with verified conductivities, but the SAP-dependent values for new dwellings (0.18/0.13/0.11 notional) are targets for the energy assessor to confirm on each job.",
 "The parametric configurators cover cavity walls, ground floors, heated basements and three roof types; timber frame walls, dormer cheeks, internal linings and separating elements are fixed build-ups and are not yet parametric.",
 "Wales, Scotland and Northern Ireland are not covered; every specification is England-only.",
 "The BuildingRegs4Plans comparison was carried out as a topic and requirement check with no text reproduced; a final proof-read of the eight documents for house style and duplication before first external issue is recommended, and the A102 General Notes drawing sheet still cites withdrawn standards."]:
    bullet(d,x)
d.save(os.path.join(OUT,'SYDS_Spec_Library_PlanCheck_Report.docx'))
subprocess.run(['soffice','--headless','--convert-to','pdf','--outdir',OUT,os.path.join(OUT,'SYDS_Spec_Library_PlanCheck_Report.docx')],check=True,capture_output=True)
print("done")
